# Generated by Django 3.1.5 on 2021-01-12 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210112_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='UserTag',
        ),
    ]
